# Generated by Django 2.2.7 on 2019-11-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_animal_animalcolors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimalColors',
            new_name='AnimalColor',
        ),
    ]
